@startuml
'https://plantuml.com/sequence-diagram

interface Function {
    + double evaluate();
    + double evaluate(int value);
    + List<String> getVariables();
    + String toString();
}

class Number implements Function {
    - double value;

    + double evaluate();
    + double evaluate(int value);
    + List<String> getVariables();
    + String toString();
}

class Variable implements Function {
    - String name;

    + double evaluate();
    + double evaluate(int value);
    + List<String> getVariables();
    + String toString();
}

class BinaryOperation implements Function {
    - Function left;
    - Function right;
    - String operation;

    + double evaluate();
    + double evaluate(int value);
    + List<String> getVariables();
    + String toString();
}

class UnaryOperation implements Function {
    - Function function;
    - String operation;

    + double evaluate();
    + double evaluate(int value);
    + List<String> getVariables();
    + String toString();
}
@enduml